CREATE OR REPLACE TABLE `meli-bi-data.SBOX_PRICING1P.INPUTS_AGG_BRAND_FRAMEWORK_PISOS`

AS



WITH UE_LAST_6_CLOSED AS (

  SELECT M.SIT_SITE_ID,
    D.VERTICAL,
    D.DOM_DOMAIN_AGG2,
    ITE_ATT_BRAND,
    CAST(SUM(UE_PRC_TGMV_AMT_LC) AS FLOAT64) AS UE_CON_TGMV_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUTION_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_REVENUE_GROSS_AMT_LC) AS FLOAT64) AS UE_MNG_REVENUE_GROSS_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC) AS FLOAT64) AS UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_CMV_AMT_LC) AS FLOAT64) AS UE_CON_CMV_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_OTHER_PRODUCT_COST_AMT_LC) AS FLOAT64) AS UE_MNG_OTHER_PRODUCT_COST_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_CONTRACOGS_AMT_LC) AS FLOAT64) AS UE_CON_CONTRACOGS_AMT_LC_L6CM,

  FROM `meli-bi-data.WHOWNER.BT_UE_OUTPUT_MNG` M
  LEFT JOIN WHOWNER.LK_ITE_ITEM_DOMAINS_2025 D ON M.SIT_SITE_ID = D.SIT_SITE_ID  AND M.ITE_ITEM_ID = D.ITE_ITEM_ID
  WHERE UE_PRC_BUSINESS_UNIT IN ('FIRST_PARTY')
    AND M.SIT_SITE_ID IN (SELECT SIT_SITE_ID FROM SBOX_PRICING1P.LISTA_SITES_1P)
    AND DATE_TRUNC(DIA_FINAL,MONTH) BETWEEN DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -2 - 6 MONTH) AND DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -2  MONTH)
  GROUP BY ALL
  ),

UE_LAST_MONTH AS (

  SELECT M.SIT_SITE_ID,
    D.VERTICAL,
    D.DOM_DOMAIN_AGG2,
    ITE_ATT_BRAND,
    CAST(SUM(UE_PRC_TGMV_AMT_LC) AS FLOAT64) AS UE_CON_TGMV_AMT_LC_LM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_AMT_LC_LM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC_LM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC_LM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC_LM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUTION_AMT_LC_LM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC_LM,
    CAST(SUM(UE_MNG_REVENUE_GROSS_AMT_LC) AS FLOAT64) AS UE_MNG_REVENUE_GROSS_AMT_LC_LM,
    CAST(SUM(UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC) AS FLOAT64) AS UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC_LM,
    CAST(SUM(UE_MNG_CMV_AMT_LC) AS FLOAT64) AS UE_CON_CMV_AMT_LC_LM,
    CAST(SUM(UE_MNG_OTHER_PRODUCT_COST_AMT_LC) AS FLOAT64) AS UE_MNG_OTHER_PRODUCT_COST_AMT_LC_LM,
    CAST(SUM(UE_MNG_CONTRACOGS_AMT_LC) AS FLOAT64) AS UE_CON_CONTRACOGS_AMT_LC_LM,

  FROM `meli-bi-data.WHOWNER.BT_UE_OUTPUT_MNG` M
  LEFT JOIN WHOWNER.LK_ITE_ITEM_DOMAINS_2025 D ON M.SIT_SITE_ID = D.SIT_SITE_ID  AND M.ITE_ITEM_ID = D.ITE_ITEM_ID
  WHERE UE_PRC_BUSINESS_UNIT IN ('FIRST_PARTY')
    AND M.SIT_SITE_ID IN (SELECT SIT_SITE_ID FROM SBOX_PRICING1P.LISTA_SITES_1P)
    AND DATE_TRUNC(DIA_FINAL,MONTH) = DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -1 MONTH) 
  GROUP BY ALL
  ),


BPC_ABC_LAST_MONTH AS (
  SELECT SIT_SITE_ID,
    VERTICAL,
    DOM_AGG_2 AS DOM_DOMAIN_AGG2,
    BRAND AS ITE_ATT_BRAND,
    COALESCE(SUM(VISITS_MATCH),0) - COALESCE(SUM(VISITS_EXPENSIVE),0) AS VISITS_COMPETITIVE,
    COALESCE(SUM(VISITS_MATCH),0) AS VISITS_MATCH,
  FROM WHOWNER.BT_COM_FAVORABILITY F
  WHERE FAVORABILITY_TYPE = 'BOX_1P_ABC'
        AND SIT_SITE_ID IN  (SELECT SIT_SITE_ID FROM SBOX_PRICING1P.LISTA_SITES_1P)
        --AND TIM_DAY >= '2025-02-07' -- ROLLOUT DE COSTO FINANCIERO
        AND DATE_TRUNC(TIM_DAY,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE(), INTERVAL -1 MONTH),MONTH)
        AND F.VISITS_MATCH > 0
  GROUP BY ALL


),

TARGET_VM AS (

  SELECT 
  PLAN_VERSION,
  SIT_SITE_ID,
  VERTICAL_DOMAIN as VERTICAL,
  DOM_DOMAIN_AGG2,
  --ITE_ITEM_BRAND AS ITE_ATT_BRAND,
  SUM(TGMV_LC) AS TGMV_LC_AGG,
  SUM(REV_GROSS_LC) AS REV_GROSS_LC_AGG,
  SUM(TSI) AS TSI_AGG,
  SUM(VENDOR_MARGIN_LC) AS VENDOR_MARGIN_LC_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(TGMV_LC)) AS VENDOR_MARGIN_PERC_TGMV_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(REV_GROSS_LC)) AS VENDOR_MARGIN_PERC_REV_AGG,
FROM WHOWNER.BT_1P_PLAN_DAILY
WHERE DATE_TRUNC(TIM_DAY,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE,INTERVAL 0 MONTH),MONTH)
  AND SIT_SITE_ID IN (SELECT SIT_SITE_ID FROM SBOX_PRICING1P.LISTA_SITES_1P)
  AND PLAN_VERSION  = 'OP25'
  --AND PLAN_VERSION = 'IBP Vigente'
  --AND PLAN_VERSION = 'IBP 1+11'
  --AND PLAN_VERSION = 'IBP 2+10'
GROUP BY ALL
ORDER BY 1,2,3,4
),


TARGET_VM_VERTICAL AS (

  SELECT 
  PLAN_VERSION,
  SIT_SITE_ID,
  VERTICAL_DOMAIN as VERTICAL,
  'ALL' AS DOM_DOMAIN_AGG2,
  --ITE_ITEM_BRAND AS ITE_ATT_BRAND,
  -- SUM(VENDOR_MARGIN_LC) AS VENDOR_MARGIN_LC_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(TGMV_LC)) AS VENDOR_MARGIN_PERC_TGMV_VERTICAL,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(REV_GROSS_LC)) AS VENDOR_MARGIN_PERC_REV_VERTICAL,
FROM WHOWNER.BT_1P_PLAN_DAILY
WHERE DATE_TRUNC(TIM_DAY,MONTH) = (SELECT MAX( DATE_TRUNC(TIM_DAY,MONTH)  ) FROM WHOWNER.BT_1P_PLAN_DAILY WHERE DATE_TRUNC(TIM_DAY,MONTH) <= DATE_TRUNC(CURRENT_DATE, MONTH) )
  AND SIT_SITE_ID IN (SELECT SIT_SITE_ID FROM SBOX_PRICING1P.LISTA_SITES_1P)
  AND PLAN_VERSION  = 'OP25'
  --AND PLAN_VERSION = 'IBP Vigente'
  --AND PLAN_VERSION = 'IBP 1+11'
  --AND PLAN_VERSION = 'IBP 2+10'
GROUP BY ALL
ORDER BY 1,2,3,4
),


TARGET_VM_SITE AS (

  SELECT 
  PLAN_VERSION,
  SIT_SITE_ID,
  'ALL' as VERTICAL,
  'ALL' AS DOM_DOMAIN_AGG2,
  --ITE_ITEM_BRAND AS ITE_ATT_BRAND,
  -- SUM(VENDOR_MARGIN_LC) AS VENDOR_MARGIN_LC_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(TGMV_LC)) AS VENDOR_MARGIN_PERC_TGMV_SITE,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(REV_GROSS_LC)) AS VENDOR_MARGIN_PERC_REV_SITE,
FROM WHOWNER.BT_1P_PLAN_DAILY
WHERE DATE_TRUNC(TIM_DAY,MONTH) = (SELECT MAX( DATE_TRUNC(TIM_DAY,MONTH)  ) FROM WHOWNER.BT_1P_PLAN_DAILY WHERE DATE_TRUNC(TIM_DAY,MONTH) <= DATE_TRUNC(CURRENT_DATE, MONTH) )
  AND SIT_SITE_ID IN (SELECT SIT_SITE_ID FROM SBOX_PRICING1P.LISTA_SITES_1P)
  AND PLAN_VERSION  = 'OP25'
  --AND PLAN_VERSION = 'IBP Vigente'
  --AND PLAN_VERSION = 'IBP 1+11'
  --AND PLAN_VERSION = 'IBP 2+10'
GROUP BY ALL
ORDER BY 1,2,3,4
)

, TGMV_USD AS (

      
    SELECT *
      ,TGMV/SUM(TGMV) OVER( ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SHARE_TGMV
    FROM (
      SELECT 
          DM.SIT_SITE_ID,
          DM.DOM_DOMAIN_AGG2,
          DM.ITE_ITEM_BRAND AS ITE_ATT_BRAND,
          SUM(TGMV) AS TGMV,
      FROM WHOWNER.DM_MKP_1P_INVENTORY_METRICS DM
      WHERE SIT_SITE_ID IN (SELECT SIT_SITE_ID FROM SBOX_PRICING1P.LISTA_SITES_1P)
          -- AND ITE_ITEM_STATUS = 'ACTIVE'
          AND DATE_TRUNC(ORD_CLOSED_DT,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE(), INTERVAL -1 MONTH),MONTH)
      GROUP BY ALL
      --ORDER BY TGMV DESC
    )
    ORDER BY SHARE_TGMV DESC
)

SELECT U.*,
  UL.UE_CON_TGMV_AMT_LC_LM,
  UL.UE_MNG_VENDOR_MARGIN_AMT_LC_LM,
  UL.UE_MNG_REVENUE_GROSS_AMT_LC_LM,
  UL.UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC_LM,
  UL.UE_CON_CMV_AMT_LC_LM,
  UL.UE_MNG_OTHER_PRODUCT_COST_AMT_LC_LM,
  UL.UE_CON_CONTRACOGS_AMT_LC_LM,
  T.TARGET_PRIORIZED
  ,CAST(TA.TGMV_LC_AGG AS FLOAT64) AS TGT_TGMV_LC_AGG
  ,CAST(TA.REV_GROSS_LC_AGG AS FLOAT64) AS TGT_REV_GROSS_LC_AGG
  ,CAST(TA.VENDOR_MARGIN_LC_AGG AS FLOAT64) AS TGT_VENDOR_MARGIN_LC_AGG
  ,CAST(COALESCE(TA.VENDOR_MARGIN_PERC_TGMV_AGG,TV.VENDOR_MARGIN_PERC_TGMV_VERTICAL,TS.VENDOR_MARGIN_PERC_TGMV_SITE) AS FLOAT64) AS TGT_VENDOR_MARGIN_PERC_TGMV
  ,CAST(COALESCE(TA.VENDOR_MARGIN_PERC_REV_AGG, TV.VENDOR_MARGIN_PERC_REV_VERTICAL, TS.VENDOR_MARGIN_PERC_REV_SITE) AS FLOAT64) AS TGT_VENDOR_MARGIN_PERC_REV
  ,CAST(B.VISITS_COMPETITIVE AS FLOAT64) AS VISITS_COMPETITIVE_ABC
  ,CAST(B.VISITS_MATCH AS FLOAT64) AS VISITS_MATCH_ABC
  ,TU.TGMV AS TGMV_USD_LM
  ,TU.SHARE_TGMV AS SHARE_TGMV_USD_LM
FROM UE_LAST_6_CLOSED AS U
LEFT JOIN UE_LAST_MONTH AS UL ON U.SIT_SITE_ID = UL.SIT_SITE_ID AND U.VERTICAL = UL.VERTICAL AND U.DOM_DOMAIN_AGG2 = UL.DOM_DOMAIN_AGG2 AND U.ITE_ATT_BRAND = UL.ITE_ATT_BRAND
LEFT JOIN SBOX_PRICING1P.TARGETS_BPC_BOX_AB_OP T ON U.SIT_SITE_ID = T.SITE AND U.VERTICAL = T.VERTICAL AND T.MONTH = EXTRACT(YEAR FROM CURRENT_DATE)*100 + EXTRACT(MONTH FROM CURRENT_DATE)
LEFT JOIN TARGET_VM AS TA ON U.SIT_SITE_ID = TA.SIT_SITE_ID AND U.DOM_DOMAIN_AGG2 = TA.DOM_DOMAIN_AGG2
LEFT JOIN TARGET_VM_VERTICAL TV ON U.SIT_SITE_ID = TV.SIT_SITE_ID AND U.VERTICAL = TV.VERTICAL
LEFT JOIN TARGET_VM_SITE TS ON U.SIT_SITE_ID = TS.SIT_SITE_ID
LEFT JOIN BPC_ABC_LAST_MONTH B ON U.SIT_SITE_ID = B.SIT_SITE_ID AND U.VERTICAL = B.VERTICAL AND U.DOM_DOMAIN_AGG2 = B.DOM_DOMAIN_AGG2 AND U.ITE_ATT_BRAND = B.ITE_ATT_BRAND
LEFT JOIN TGMV_USD TU ON U.SIT_SITE_ID = TU.SIT_SITE_ID AND U.DOM_DOMAIN_AGG2 = TU.DOM_DOMAIN_AGG2 AND U.ITE_ATT_BRAND = TU.ITE_ATT_BRAND
-- TRAZER targets de VM POR AGG BRAND