WITH UE_LAST_6_CLOSED AS (

  SELECT M.SIT_SITE_ID,
    D.VERTICAL,
    D.DOM_DOMAIN_AGG2,
    ITE_ATT_BRAND,
    CAST(SUM(UE_CON_TGMV_AMT_LC) AS FLOAT64) AS UE_CON_TGMV_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUTION_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_REVENUE_GROSS_AMT_LC) AS FLOAT64) AS UE_MNG_REVENUE_GROSS_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC) AS FLOAT64) AS UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC_L6CM,
    CAST(SUM(UE_CON_CMV_AMT_LC) AS FLOAT64) AS UE_CON_CMV_AMT_LC_L6CM,
    CAST(SUM(UE_MNG_OTHER_PRODUCT_COST_AMT_LC) AS FLOAT64) AS UE_MNG_OTHER_PRODUCT_COST_AMT_LC_L6CM,
    CAST(SUM(UE_CON_CONTRACOGS_AMT_LC) AS FLOAT64) AS UE_CON_CONTRACOGS_AMT_LC_L6CM,

  FROM `meli-bi-data.WHOWNER.BT_UE_OUTPUT_MANAGERIAL` M
  LEFT JOIN WHOWNER.LK_ITE_ITEM_DOMAINS_2025 D ON M.SIT_SITE_ID = D.SIT_SITE_ID  AND M.ITE_ITEM_ID = D.ITE_ITEM_ID
  WHERE UE_PRC_BUSINESS_UNIT IN ('FIRST_PARTY')
    AND M.SIT_SITE_ID IN ('MLB','MLM','MLA','MCO', 'MLC')
    AND DATE_TRUNC(DIA_FINAL,MONTH) BETWEEN DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -2 - 6 MONTH) AND DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -2  MONTH)
  GROUP BY ALL
  ),

UE_LAST_MONTH AS (

  SELECT M.SIT_SITE_ID,
    D.VERTICAL,
    D.DOM_DOMAIN_AGG2,
    ITE_ATT_BRAND,
    CAST(SUM(UE_CON_TGMV_AMT_LC) AS FLOAT64) AS UE_CON_TGMV_AMT_LC_LM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_AMT_LC_LM,
    CAST(SUM(UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VENDOR_MARGIN_ADJ_AMT_LC_LM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_AMT_LC_LM,
    CAST(SUM(UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_VARIABLE_CONTRIBUTION_ADJ_AMT_LC_LM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUTION_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUTION_AMT_LC_LM,
    CAST(SUM(UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC) AS FLOAT64) AS UE_MNG_DIRECT_CONTRIBUITION_ADJ_AMT_LC_LM,
    CAST(SUM(UE_MNG_REVENUE_GROSS_AMT_LC) AS FLOAT64) AS UE_MNG_REVENUE_GROSS_AMT_LC_LM,
    CAST(SUM(UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC) AS FLOAT64) AS UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC_LM,
    CAST(SUM(UE_CON_CMV_AMT_LC) AS FLOAT64) AS UE_CON_CMV_AMT_LC_LM,
    CAST(SUM(UE_MNG_OTHER_PRODUCT_COST_AMT_LC) AS FLOAT64) AS UE_MNG_OTHER_PRODUCT_COST_AMT_LC_LM,
    CAST(SUM(UE_CON_CONTRACOGS_AMT_LC) AS FLOAT64) AS UE_CON_CONTRACOGS_AMT_LC_LM,

  FROM `meli-bi-data.WHOWNER.BT_UE_OUTPUT_MANAGERIAL` M
  LEFT JOIN WHOWNER.LK_ITE_ITEM_DOMAINS_2025 D ON M.SIT_SITE_ID = D.SIT_SITE_ID  AND M.ITE_ITEM_ID = D.ITE_ITEM_ID
  WHERE UE_PRC_BUSINESS_UNIT IN ('FIRST_PARTY')
    AND M.SIT_SITE_ID IN ('MLB','MLM','MLA','MCO', 'MLC')
    AND DATE_TRUNC(DIA_FINAL,MONTH) = DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -1 MONTH) 
  GROUP BY ALL
  ),

TARGET_VM AS (

  SELECT 
  PLAN_VERSION,
  SIT_SITE_ID,
  VERTICAL_DOMAIN as VERTICAL,
  DOM_DOMAIN_AGG2,
  --ITE_ITEM_BRAND AS ITE_ATT_BRAND,
  SUM(TGMV_LC) AS TGMV_LC_AGG,
  SUM(REV_GROSS_LC) AS REV_GROSS_LC_AGG,
  SUM(TSI) AS TSI_AGG,
  SUM(VENDOR_MARGIN_LC) AS VENDOR_MARGIN_LC_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(TGMV_LC)) AS VENDOR_MARGIN_PERC_TGMV_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(REV_GROSS_LC)) AS VENDOR_MARGIN_PERC_REV_AGG,
FROM WHOWNER.BT_1P_PLAN_DAILY
WHERE DATE_TRUNC(TIM_DAY,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE,INTERVAL 0 MONTH),MONTH)
  AND SIT_SITE_ID IN ('MLB', 'MLM', 'MLA', 'MLC', 'MCO')
  AND PLAN_VERSION  = 'OP25'
  --AND PLAN_VERSION = 'IBP Vigente'
  --AND PLAN_VERSION = 'IBP 1+11'
  --AND PLAN_VERSION = 'IBP 2+10'
GROUP BY ALL
ORDER BY 1,2,3,4
),


TARGET_VM_VERTICAL AS (

  SELECT 
  PLAN_VERSION,
  SIT_SITE_ID,
  VERTICAL_DOMAIN as VERTICAL,
  'ALL' AS DOM_DOMAIN_AGG2,
  --ITE_ITEM_BRAND AS ITE_ATT_BRAND,
  -- SUM(VENDOR_MARGIN_LC) AS VENDOR_MARGIN_LC_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(TGMV_LC)) AS VENDOR_MARGIN_PERC_TGMV_VERTICAL,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(REV_GROSS_LC)) AS VENDOR_MARGIN_PERC_REV_VERTICAL,
FROM WHOWNER.BT_1P_PLAN_DAILY
WHERE DATE_TRUNC(TIM_DAY,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE,INTERVAL 0 MONTH),MONTH)
  AND SIT_SITE_ID IN ('MLB', 'MLM', 'MLA', 'MLC', 'MCO')
  AND PLAN_VERSION  = 'OP25'
  --AND PLAN_VERSION = 'IBP Vigente'
  --AND PLAN_VERSION = 'IBP 1+11'
  --AND PLAN_VERSION = 'IBP 2+10'
GROUP BY ALL
ORDER BY 1,2,3,4
),


TARGET_VM_SITE AS (

  SELECT 
  PLAN_VERSION,
  SIT_SITE_ID,
  'ALL' as VERTICAL,
  'ALL' AS DOM_DOMAIN_AGG2,
  --ITE_ITEM_BRAND AS ITE_ATT_BRAND,
  -- SUM(VENDOR_MARGIN_LC) AS VENDOR_MARGIN_LC_AGG,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(TGMV_LC)) AS VENDOR_MARGIN_PERC_TGMV_SITE,
  SAFE_DIVIDE(SUM(VENDOR_MARGIN_LC),SUM(REV_GROSS_LC)) AS VENDOR_MARGIN_PERC_REV_SITE,
FROM WHOWNER.BT_1P_PLAN_DAILY
WHERE DATE_TRUNC(TIM_DAY,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE,INTERVAL 0 MONTH),MONTH)
  AND SIT_SITE_ID IN ('MLB', 'MLM', 'MLA', 'MLC', 'MCO')
  AND PLAN_VERSION  = 'OP25'
  --AND PLAN_VERSION = 'IBP Vigente'
  --AND PLAN_VERSION = 'IBP 1+11'
  --AND PLAN_VERSION = 'IBP 2+10'
GROUP BY ALL
ORDER BY 1,2,3,4
)

SELECT U.*,
  UL.UE_CON_TGMV_AMT_LC_LM,
  UL.UE_MNG_VENDOR_MARGIN_AMT_LC_LM,
  UL.UE_MNG_REVENUE_GROSS_AMT_LC_LM,
  UL.UE_MNG_NON_BANK_COUPONS_DISCOUNT_AMT_LC_LM,
  UL.UE_CON_CMV_AMT_LC_LM,
  UL.UE_MNG_OTHER_PRODUCT_COST_AMT_LC_LM,
  UL.UE_CON_CONTRACOGS_AMT_LC_LM,
  T.TARGET_PRIORIZED
  ,CAST(TA.TGMV_LC_AGG AS FLOAT64) AS TGT_TGMV_LC_AGG
  ,CAST(TA.REV_GROSS_LC_AGG AS FLOAT64) AS TGT_REV_GROSS_LC_AGG
  ,CAST(TA.VENDOR_MARGIN_LC_AGG AS FLOAT64) AS TGT_VENDOR_MARGIN_LC_AGG
  ,CAST(COALESCE(TA.VENDOR_MARGIN_PERC_TGMV_AGG,TV.VENDOR_MARGIN_PERC_TGMV_VERTICAL,TS.VENDOR_MARGIN_PERC_TGMV_SITE) AS FLOAT64) AS TGT_VENDOR_MARGIN_PERC_TGMV
  ,CAST(COALESCE(TA.VENDOR_MARGIN_PERC_REV_AGG, TV.VENDOR_MARGIN_PERC_REV_VERTICAL, TS.VENDOR_MARGIN_PERC_REV_SITE) AS FLOAT64) AS TGT_VENDOR_MARGIN_PERC_REV
FROM UE_LAST_6_CLOSED AS U
LEFT JOIN UE_LAST_MONTH AS UL ON U.SIT_SITE_ID = UL.SIT_SITE_ID AND U.VERTICAL = UL.VERTICAL AND U.DOM_DOMAIN_AGG2 = UL.DOM_DOMAIN_AGG2 AND U.ITE_ATT_BRAND = UL.ITE_ATT_BRAND
LEFT JOIN SBOX_PRICING1P.TARGETS_BPC_LANDED_AB_2025 T ON U.SIT_SITE_ID = T.SITE AND U.VERTICAL = T.VERTICAL AND T.MONTH = EXTRACT(YEAR FROM CURRENT_DATE)*100 + EXTRACT(MONTH FROM CURRENT_DATE)
LEFT JOIN TARGET_VM AS TA ON U.SIT_SITE_ID = TA.SIT_SITE_ID AND U.DOM_DOMAIN_AGG2 = TA.DOM_DOMAIN_AGG2
LEFT JOIN TARGET_VM_VERTICAL TV ON U.SIT_SITE_ID = TV.SIT_SITE_ID AND U.VERTICAL = TV.VERTICAL
LEFT JOIN TARGET_VM_SITE TS ON U.SIT_SITE_ID = TS.SIT_SITE_ID
-- TRAZER targets de VM POR AGG BRAND