WITH BPC_DATA AS (

    SELECT F.TIM_DAY
        ,F.SIT_SITE_ID
        --,F.MELI_ID_TYPE
        ,F.MELI_ID
        ,F.FAVORABILITY_TYPE
        ,F.ITE_ITEM_ID
        ,CONCAT(F.SIT_SITE_ID, F.ITE_ITEM_ID) AS ITEM_ID
        ,F.DOM_AGG_2 AS DOM_DOMAIN_AGG2
        ,F.BRAND
        ,F.PRICE_MELI
        ,F.COMP_ITEM_ID_WINNER
        ,F.COMP_PRICE_RIVAL
        --,F.VISITS_TOTAL
        ,F.VISITS_MATCH
        ,F.VISITS_EXPENSIVE
        , COALESCE(F.VISITS_MATCH,0)- COALESCE(F.VISITS_EXPENSIVE,0) AS VISITS_COMPETITIVE
    FROM `WHOWNER.BT_COM_FAVORABILITY`F 
    WHERE FAVORABILITY_TYPE = 'LANDED_1P_AB'
        AND SIT_SITE_ID IN  ('MLB','MLM', 'MLC', 'MCO', 'MLA')
        --AND TIM_DAY >= '2025-02-07' -- ROLLOUT DE COSTO FINANCIERO
        AND DATE_TRUNC(TIM_DAY,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE(), INTERVAL -1 MONTH),MONTH)
        AND F.VISITS_MATCH > 0

),

FLOOR_INFO AS (

    SELECT CAST(UPDATED_DATE AS DATE) AS TIM_DAY
    ,ITEM_ID
    ,COST
    ,CCOGS
    ,SIT_SITE_IVA
    ,FINANCIAL_COST
    ,INSTALLMENTS
    ,PPM_PROFIT_FLOOR
    ,PPM_CALCULATED_FLOOR_PRICE
    ,UPDATED_DATE
    ,ROW_NUMBER() OVER (PARTITION BY CAST(UPDATED_DATE AS DATE) , ITEM_ID ORDER BY UPDATED_DATE DESC) AS RW
    FROM WHOWNER.LK_PL1P_UE_MATERIAL_SUMMARIZATION_HISTORY
    WHERE UPDATED_DATE >= '2024-01-01'
    QUALIFY RW = 1

),




ELASTICIDAD AS ( -- Trazer a elasticidade por AGG2
  WITH 
  
  TGMV_TOTAL_ITEM AS (
  
  SELECT 
    --TIM_DAY,
    SIT_SITE_ID,
    ITE_ITEM_ID,
    DOM_DOMAIN_AGG2,
    SUM(COALESCE(TGMV_IVA_DEDUCTED_LC,0)) AS TGMV_IVA_DEDUCTED_LC,
  FROM WHOWNER.DM_MKP_PL1P_PRICING
  WHERE 1=1
      AND SIT_SITE_ID IN ('MLB','MLM', 'MLC', 'MCO', 'MLA')
      AND DATE_TRUNC(TIM_DAY,MONTH) = DATE_TRUNC(DATE_ADD(CURRENT_DATE(), INTERVAL -1 MONTH),MONTH)
      AND TGMV_IVA_DEDUCTED_LC > 0

  GROUP BY ALL

  )



  SELECT  
    TTI.SIT_SITE_ID,
    TTI.DOM_DOMAIN_AGG2,
    SUM(B * TGMV_IVA_DEDUCTED_LC)/SUM(TGMV_IVA_DEDUCTED_LC) AS B,      
  FROM TGMV_TOTAL_ITEM TTI
  LEFT JOIN meli-bi-data.WHOWNER.DM_PL1P_ELAST_ITEMS_OUTPUT E ON TTI.SIT_SITE_ID = E.SIT_SITE_ID  AND TTI.ITE_ITEM_ID = E.ITE_ITEM_ID
  WHERE TTI.SIT_SITE_ID  IN ('MLB','MLM', 'MLC', 'MCO', 'MLA')
    AND B IS NOT NULL
  GROUP BY ALL

UNION ALL   


 SELECT  
    TTI.SIT_SITE_ID,
    'TOTAL_SITE' AS DOM_DOMAIN_AGG2,
    SUM(B * TGMV_IVA_DEDUCTED_LC)/SUM(TGMV_IVA_DEDUCTED_LC) AS B,      
  FROM TGMV_TOTAL_ITEM TTI
  LEFT JOIN meli-bi-data.WHOWNER.DM_PL1P_ELAST_ITEMS_OUTPUT E ON TTI.SIT_SITE_ID = E.SIT_SITE_ID  AND TTI.ITE_ITEM_ID = E.ITE_ITEM_ID
  WHERE TTI.SIT_SITE_ID  IN ('MLB','MLM', 'MLC', 'MCO', 'MLA')
    AND B IS NOT NULL
  GROUP BY ALL
),

JOIN_TABLE AS (
    SELECT B.*
        ,F.COST
        ,F.CCOGS
        ,F.SIT_SITE_IVA
        ,F.FINANCIAL_COST
        ,F.INSTALLMENTS
        ,F.PPM_PROFIT_FLOOR
        ,F.PPM_CALCULATED_FLOOR_PRICE
        ,F.UPDATED_DATE
        ,ROW_NUMBER() OVER (PARTITION BY B.ITEM_ID, B.TIM_DAY ORDER BY F.UPDATED_DATE DESC) AS RW
    FROM BPC_DATA AS B
    LEFT JOIN FLOOR_INFO F ON B.ITEM_ID = F.ITEM_ID AND B.TIM_DAY >= F.TIM_DAY
    QUALIFY RW =1

),


FINAL_TABLE AS (
    SELECT J.*,
        E_AGG2.B AS B_AGG2,
        E_TS.B AS B_TOTAL_STE,
        COALESCE(E_AGG2.B,E_TS.B) AS B_EFECTIVO
    FROM JOIN_TABLE J
    LEFT JOIN ELASTICIDAD E_AGG2 ON J.SIT_SITE_ID = E_AGG2.SIT_SITE_ID AND J.DOM_DOMAIN_AGG2 = E_AGG2.DOM_DOMAIN_AGG2
    LEFT JOIN ELASTICIDAD E_TS ON J.SIT_SITE_ID = E_TS.SIT_SITE_ID AND E_TS.DOM_DOMAIN_AGG2 = 'TOTAL_SITE'

)

SELECT *
FROM FINAL_TABLE