WITH ITEMS AS (

    SELECT SIT_SITE_ID,
    ITE_ITEM_ID,
    ITE_ITEM_STATUS,
    ITE_ITEM_INVENTORY_ID,
    ITE_ITEM_QUANTITY_AVAILABLE,
    ITE_ITEM_CATALOG_LISTING_FLG,
    ITE_ITEM_RELATIONS

    FROM WHOWNER.LK_ITE_ITEMS
    WHERE ITE_ITEM_PARTY_TYPE_ID = '1P'
    AND SIT_SITE_ID  IN ('MLB','MLA','MLC','MLM','MCO')
    AND ITE_ITEM_STATUS IN ('active','paused')
    AND ITE_ITEM_QUANTITY_AVAILABLE > 0
    AND ITE_ITEM_INVENTORY_ID IS NOT NULL
    AND IS_TEST = FALSE

)

, CATALOGO_HERMANADO AS (
    SELECT SIT_SITE_ID,
        ITE_ITEM_ID,
        FROM (
        SELECT 
            SIT_SITE_ID,
            ITE_ITEM_ID,
            R.ITEM_ID,
        FROM ITEMS, UNNEST(ITE_ITEM_RELATIONS) R
        WHERE ITE_ITEM_CATALOG_LISTING_FLG = TRUE
        )
        GROUP BY 1,2
)

SELECT I.SIT_SITE_ID,
    I.ITE_ITEM_ID,
    I.ITE_ITEM_STATUS,
    I.ITE_ITEM_INVENTORY_ID,
    I.ITE_ITEM_QUANTITY_AVAILABLE,
    I.ITE_ITEM_CATALOG_LISTING_FLG,
    CASE WHEN C.ITE_ITEM_ID IS NULL AND ITE_ITEM_CATALOG_LISTING_FLG = TRUE THEN 1 ELSE 0 END AS FLAG_CATALOGO_NO_HERMANADO,
FROM ITEMS I
LEFT JOIN CATALOGO_HERMANADO C ON I.SIT_SITE_ID = C.SIT_SITE_ID AND I.ITE_ITEM_ID = C.ITE_ITEM_ID
WHERE 
    (ITE_ITEM_CATALOG_LISTING_FLG = FALSE
    OR
    (ITE_ITEM_CATALOG_LISTING_FLG = TRUE AND C.ITE_ITEM_ID IS NULL) -- ITEMS DE CATALOGO SEM HERMANADOS
    ) 