SELECT SIT_SITE_ID,
  ITE_ITEM_ID,
  ITE_ITEM_STATUS,
  ITE_ITEM_INVENTORY_ID,
  ITE_ITEM_QUANTITY_AVAILABLE,

FROM WHOWNER.LK_ITE_ITEMS
WHERE ITE_ITEM_PARTY_TYPE_ID = '1P'
  AND SIT_SITE_ID  IN ('MLB','MLA','MLC','MLM','MCO')
  AND ITE_ITEM_STATUS IN ('active','paused')
  AND ITE_ITEM_QUANTITY_AVAILABLE > 0
  AND ITE_ITEM_INVENTORY_ID IS NOT NULL