SELECT
    BB.TIM_DAY,
    EXTRACT(YEAR FROM BB.TIM_DAY) *100 + EXTRACT(WEEK FROM BB.TIM_DAY) AS WEEK,
    EXTRACT(YEAR FROM BB.TIM_DAY) *100 + EXTRACT(MONTH FROM BB.TIM_DAY) AS MONTH,
    EXTRACT(YEAR FROM BB.TIM_DAY) *100 + EXTRACT(QUARTER FROM BB.TIM_DAY) AS QUARTER,    
    BB.SIT_SITE_ID,
    BB.ITE_ITEM_ID,
    BB.VERTICAL,
    BB.DOM_DOMAIN_AGG1,
    BB.DOM_DOMAIN_AGG2,
    BB.ITE_ATT_BRAND,
    SUM(CASE WHEN STATUS_BB_1P = 'pierde_1p' then TOTAL_VISITS_BB ELSE 0 END) AS VISITS_LBB,
    SUM(TOTAL_VISITS_BB) AS VISITAS,
    (COALESCE(SUM(TOTAL_VISITS_BB),0) - COALESCE(SUM(VISITS_1P),0)) AS VISITS_LBB_V,
FROM meli-bi-data.WHOWNER.DM_PL1P_PRICING_BUYBOX_PH BB
WHERE BB.SIT_SITE_ID IN ('MLB','MLM','MLC','MLA','MCO')
    AND BB.TIM_DAY >= '2022-12-01'
GROUP BY ALL