WITH ITEMS_CATALOGO AS (

    SELECT SIT_SITE_ID
        ,ITE_ATT_BRAND
        ,ITE_ITEM_ID
        ,ITE_ITEM_STATUS
        ,ITE_ITEM_BLACKLIST
        ,ITE_ITEM_CATALOG_LISTING_FLG
        ,PROFITABILITY_BUYBOX_FLOOR_RENT
        ,PROFITABILITY_BUYBOX_FLOOR_VALUE
        ,ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, ITE_ITEM_ID ORDER BY LAST_UPDATED_FROM_DTTM DESC) as RW
    FROM `meli-bi-data.WHOWNER.LK_PL1P_PRICING_OPPS`
    WHERE 1=1
        AND ITE_ITEM_STATUS = 'ACTIVE'
        AND ITE_ITEM_BLACKLIST != 'ALL' --REMOVENDO ITENS EM BLACKLIST
        AND ITE_ITEM_CATALOG_LISTING_FLG = True -- MANTENDO APENAS ITENS DE CATALOGO
        AND DATE(LAST_UPDATED_FROM_DTTM) <= DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)
        AND DATE(LAST_UPDATED_TO_DTTM) >= DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)
    QUALIFY  RW = 1
)

, ITEMS_HERMANADOS AS (
    SELECT IH.SIT_SITE_ID
        ,IH.ITE_ITEM_ID
        ,R.ITEM_ID AS ITEM_ID_HERMANADO
        ,PO.PROFITABILITY_BUYBOX_FLOOR_RENT
        ,PO.PROFITABILITY_BUYBOX_FLOOR_VALUE
        ,ROW_NUMBER() OVER(PARTITION BY PO.SIT_SITE_ID, PO.ITE_ITEM_ID ORDER BY PO.LAST_UPDATED_FROM_DTTM DESC) as RW
    FROM `meli-bi-data.WHOWNER.LK_ITE_ITEMS` IH, unnest (ITE_ITEM_RELATIONS) as R  
    LEFT JOIN `meli-bi-data.WHOWNER.LK_PL1P_PRICING_OPPS` PO ON IH.SIT_SITE_ID = PO.SIT_SITE_ID AND R.ITEM_ID = PO.ITE_ITEM_ID
    WHERE IH.ITE_ITEM_PARTY_TYPE_ID = '1P'
        AND CONCAT(IH.SIT_SITE_ID , CAST(IH.ITE_ITEM_ID AS STRING)) IN (SELECT CONCAT(IC.SIT_SITE_ID , CAST(IC.ITE_ITEM_ID AS STRING)) FROM ITEMS_CATALOGO IC)
        AND PO.ITE_ITEM_STATUS = 'ACTIVE'
        AND PO.ITE_ITEM_BLACKLIST != 'ALL' --REMOVENDO ITENS EM BLACKLIST
        AND PO.ITE_ITEM_CATALOG_LISTING_FLG = False -- TRAZENDO SOMENTE ITENS DE LISTADO HERMANADOS
        AND DATE(PO.LAST_UPDATED_FROM_DTTM) <= DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)
        AND DATE(PO.LAST_UPDATED_TO_DTTM) >= DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)
    QUALIFY  RW = 1
)

,JOIN_TABLE AS (
    SELECT IC.SIT_SITE_ID
      ,IC.ITE_ATT_BRAND
        ,IC.ITE_ITEM_ID 
        ,IC.ITE_ITEM_STATUS
        ,IC.ITE_ITEM_BLACKLIST
        ,IC.ITE_ITEM_CATALOG_LISTING_FLG
        ,COALESCE(IH.ITEM_ID_HERMANADO,IC.ITE_ITEM_ID) AS ITE_ITEM_REF -- ITEM DE REFERENCIA PARA A ESTRATEGIA DE BBWINNER
        ,COALESCE(IH.PROFITABILITY_BUYBOX_FLOOR_RENT, IC.PROFITABILITY_BUYBOX_FLOOR_RENT) AS PROFITABILITY_BUYBOX_FLOOR_RENT
        ,COALESCE(IH.PROFITABILITY_BUYBOX_FLOOR_VALUE, IC.PROFITABILITY_BUYBOX_FLOOR_VALUE) AS PROFITABILITY_BUYBOX_FLOOR_VALUE
,pa.VISITAS_1P
        ,pa.VISITS_TOTALES

    FROM ITEMS_CATALOGO IC
    LEFT JOIN ITEMS_HERMANADOS IH ON IC.SIT_SITE_ID = IH.SIT_SITE_ID AND IC.ITE_ITEM_ID = IH.ITE_ITEM_ID
    LEFT JOIN SBOX_PRICING1P.VISITAS_TOTALES pa ON pa.TIM_day = DATE(DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)) and pa.ITE_ITEM_ID = IC.ITE_ITEM_ID AND IC.SIT_SITE_ID = pa.SIT_SITE_ID
)

SELECT J.*
    ,L.ITE_ITEM_PRICE
    ,L.ITE_ITEM_STATUS AS BB_STRATEGY_STATUS
    ,L.BUYBOX_WINNER
    ,L.CURRENT_PRICE
    ,L.PRICE_TO_WIN
    ,L.CURRENT_PROFITABILITY_PRICE
    ,SAFE.PARSE_JSON(L.PROFITABILITY_PARAMETERS) AS PROFITABILITY_PARAMETERS
    ,L.PROFITABILITY_OFFSET
    ,L.TARGET_PROFITABILITY_PRICE
    ,L.STATUS_REASON
    ,L.UPLOAD_DTTM
    ,D.VERTICAL
    ,D.DOM_DOMAIN_AGG1
    ,D.DOM_DOMAIN_AGG2
    ,ROW_NUMBER() OVER (PARTITION BY L.SIT_SITE_ID, L.ITE_ITEM_ID ORDER BY L.UPLOAD_DTTM DESC) AS RW


    ,NULL AS contracoogs
    ,NULL AS iva
    ,NULL AS suggested_profit_percentage
    ,NULL AS unit_cost
    ,NULL AS PPM_PISO_BUYBOX

    -- ,CAST(JSON_VALUE(SAFE.PARSE_JSON(L.PROFITABILITY_PARAMETERS), '$.contracoogs') AS NUMERIC) AS contracoogs
    -- ,CAST(JSON_VALUE(SAFE.PARSE_JSON(L.PROFITABILITY_PARAMETERS), '$.iva') AS NUMERIC) AS iva
    -- ,CAST(JSON_VALUE(SAFE.PARSE_JSON(L.PROFITABILITY_PARAMETERS), '$.suggested_profit_percentage') AS NUMERIC) AS suggested_profit_percentage
    -- ,CAST(JSON_VALUE(SAFE.PARSE_JSON(L.PROFITABILITY_PARAMETERS), '$.unit_cost') AS NUMERIC) AS unit_cost
    -- ,CAST(JSON_VALUE(SAFE.PARSE_JSON(L.PROFITABILITY_PARAMETERS), '$.suggested_profit_percentage') AS NUMERIC) + (CASE WHEN L.PROFITABILITY_OFFSET >= 0 THEN L.PROFITABILITY_OFFSET ELSE NULL END)  AS PPM_PISO_BUYBOX
FROM JOIN_TABLE J
LEFT JOIN `pdme000246-ula7eql32mj-furyid.TBL.LK_BUYBOX_WINNER_PRICE` L ON J.SIT_SITE_ID = L.SIT_SITE_ID AND J.ITE_ITEM_REF = L.ITE_ITEM_ID
LEFT JOIN `meli-bi-data.WHOWNER.LK_BUYBOX_PRODUCT_STATUS_PH`  B ON DATE(DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)) = B.PHOTO_ID AND J.SIT_SITE_ID = B.SIT_SITE_ID AND L.PRD_PRODUCT_ID = CONCAT(B.SIT_SITE_ID , CAST(B.PRD_PRODUCT_ID AS STRING))
LEFT JOIN `meli-bi-data.WHOWNER.LK_ITE_ITEM_DOMAINS` D ON J.SIT_SITE_ID = D.SIT_SITE_ID AND J.ITE_ITEM_ID = D.ITE_ITEM_ID
WHERE B.STATUS = 'active'
    AND DATE(L.UPLOAD_DTTM) <= DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)
    AND DATE(L.UPLOAD_DTTM) >= '2024-01-01'
QUALIFY RW = 1