WITH T1 AS (

    SELECT P.TIM_DAY,
        CAST(CASE WHEN EXTRACT(QUARTER FROM P.TIM_DAY) < 10 THEN CONCAT(EXTRACT(YEAR FROM P.TIM_DAY),'0',EXTRACT(QUARTER FROM P.TIM_DAY)) ELSE CONCAT(EXTRACT(YEAR FROM P.TIM_DAY),EXTRACT(QUARTER FROM P.TIM_DAY)) END AS INT) AS QUARTER,  
        CAST(CASE WHEN EXTRACT(MONTH FROM P.TIM_DAY) < 10 THEN CONCAT(EXTRACT(YEAR FROM P.TIM_DAY),'0',EXTRACT(MONTH FROM P.TIM_DAY)) ELSE CONCAT(EXTRACT(YEAR FROM P.TIM_DAY),EXTRACT(MONTH FROM P.TIM_DAY)) END AS INT) AS MONTH,  
        CAST(CASE WHEN EXTRACT(WEEK FROM P.TIM_DAY) < 10 THEN CONCAT(EXTRACT(YEAR FROM P.TIM_DAY),'0',EXTRACT(WEEK FROM P.TIM_DAY)) ELSE CONCAT(EXTRACT(YEAR FROM P.TIM_DAY),EXTRACT(WEEK FROM P.TIM_DAY)) END AS INT) AS WEEK,  
        CASE WHEN EXTRACT (YEAR FROM DATE_TRUNC(P.TIM_DAY, WEEK)) = EXTRACT(YEAR FROM DATE_ADD(DATE_TRUNC(P.TIM_DAY, WEEK), INTERVAL 6 DAY)) 
            THEN
            CONCAT(CAST(DATE_TRUNC(P.TIM_DAY, WEEK)  AS STRING), " to ",CAST(DATE_ADD(DATE_TRUNC(P.TIM_DAY, WEEK), INTERVAL 6 DAY) AS STRING))
            ELSE 
            CONCAT(CAST(DATE_TRUNC(P.TIM_DAY, WEEK)  AS STRING), " to ",CAST(DATE(EXTRACT (YEAR FROM DATE_TRUNC(P.TIM_DAY, WEEK)),12,31) AS STRING)) 
            END AS WEEK_DETAIL,
        P.SIT_SITE_ID,
        P.ITE_ITEM_ID,
        P.VERTICAL,
        CASE 
            WHEN P.DOM_DOMAIN_AGG1 IN ('FOOTWEAR','APPAREL ACCESSORIES','APPAREL') THEN 'APPAREL'
            WHEN P.DOM_DOMAIN_AGG1 IN ('BEAUTY') THEN 'BEAUTY'
            ELSE NULL END AS SUBVERTICAL,
        P.DOM_DOMAIN_AGG1,
        P.DOM_DOMAIN_AGG2,
        P.ITE_ATT_BRAND,
        VD.SAP_VENDOR_ESTIMATED,
        CASE 
            WHEN TYPE_PRICE_DEFINITION_DETAIL IN ('1-Blacklist','2-Manual Strategy','3-Tier wo/CCogs','4-DoD & Lightning wo/CCogs') THEN 'Manual Pricing'
            WHEN TYPE_PRICE_DEFINITION_DETAIL IN ('5-Tier w/CCogs','6-DoD & Lightning w/CCogs','7-Automatic Strategies','3a-Tier wo/CCogs exception','4a-DoD & Lightning wo/CCogs exception') THEN 'Automatic Pricing' 
            ELSE 'REVIEW' END AS  TYPE_PRICING_AUTOMATIC_MANUAL,
        PL1P_PRICING_CURRENT_WINNING_STRATEGY as PL1P_PRICING_CURRENT_WINNING_STRATEGY,
        PL1P_PRICING_CURRENT_WINNING_STRATEGY as PL1P_PRICING_CURRENT_WINNING_STRATEGY_2,
        I.ITE_ITEM_SUPERMARKET_FLG,
        I.ITE_ITEM_SCHEDULED_FLG,
        CASE WHEN COALESCE(P.ITE_SITE_CURRENT_PRICE,0) >= COALESCE(P.PROFITABILITY_PRICE_VALUE,0) THEN 1 ELSE 0 END as FLAG_PRICE_ABOVE_FLOOR,
        CASE 
            WHEN  PL1P_PRICING_CURRENT_WINNING_STRATEGY IN ('DEAL','PROMO') AND TYPE_PRICE_DEFINITION_DETAIL IN ('3-Tier wo/CCogs' , '4-DoD & Flash wo/CCogs','3a-Tier wo/CCogs exception','4a-DoD & Lightning wo/CCogs exception' )   AND COALESCE(P.ITE_SITE_CURRENT_PRICE,0) >= COALESCE(P.PROFITABILITY_PRICE_VALUE,0) THEN  'Deal arriba del piso w/o CCOGS'
            WHEN  PL1P_PRICING_CURRENT_WINNING_STRATEGY IN ('DEAL','PROMO') AND TYPE_PRICE_DEFINITION_DETAIL IN ('3-Tier wo/CCogs' , '4-DoD & Flash wo/CCogs','3a-Tier wo/CCogs exception','4a-DoD & Lightning wo/CCogs exception' )   AND COALESCE(P.ITE_SITE_CURRENT_PRICE,0) < COALESCE(P.PROFITABILITY_PRICE_VALUE,0) THEN  'Deal abajo del piso w/o CCOGS'
            WHEN  PL1P_PRICING_CURRENT_WINNING_STRATEGY IN ('DEAL','PROMO') AND TYPE_PRICE_DEFINITION_DETAIL IN ('5-Tier w/CCogs','6-DoD & Lightning w/CCogs' )   AND COALESCE(P.ITE_SITE_CURRENT_PRICE,0) >= COALESCE(P.PROFITABILITY_PRICE_VALUE,0) THEN  'Deal arriba del piso w CCOGS'
            WHEN  PL1P_PRICING_CURRENT_WINNING_STRATEGY IN ('DEAL','PROMO') AND TYPE_PRICE_DEFINITION_DETAIL IN ('5-Tier w/CCogs','6-DoD & Lightning w/CCogs' )   AND COALESCE(P.ITE_SITE_CURRENT_PRICE,0) < COALESCE(P.PROFITABILITY_PRICE_VALUE,0) THEN  'Deal abajo del piso w CCOGS'
            ELSE 'Non Deal'
            END AS DEAL_DETAIL,
        SUM(COALESCE(TOTAL_VISITS_PRODUCTS,0)) AS VISITS_TOTAL,
        SUM(CASE WHEN TYPE_PRICE_DEFINITION_DETAIL IN ('5-Tier w/CCogs','6-DoD & Lightning w/CCogs','7-Automatic Strategies') THEN TOTAL_VISITS_PRODUCTS ELSE 0 END) AS VISITS_AUTOMATICL_PRICE,
        SUM(TSI) AS TSI,
        SUM(TGMV_LC) AS TGMV,
        SUM(TSI_VALUED_ESTIMATED_LC) AS TSI_VALUED_ESTIMATED,
        SUM(AGREEMENT_AMOUNT_ESTIMATED_LC) AS AGREEMENT_AMOUNT_ESTIMATED_LC,
        SUM(TCOUPON_AMOUNT_IVA_DEDUCTED_LC) AS TCOUPON_AMOUNT_IVA_DEDUCTED_LC,
        SUM(P.PL1P_TIME_IN_STATUS_PERC)  AS PL1P_TIME_IN_STATUS_PERC,

    FROM WHOWNER.DM_MKP_PL1P_PRICING AS P
    LEFT JOIN     
        (SELECT *
            , ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, ITE_ITEM_ID ORDER BY CASE WHEN SAP_VENDOR_ESTIMATED  IS NOT NULL THEN 1 ELSE 0 END DESC ) AS RW 
            FROM meli-bi-data.SBOX_PLANNING_1P.VW_BRANDS_VENDORS_ITEM_ID 
            QUALIFY RW =1
            ) VD ON P.SIT_SITE_ID = VD.SIT_SITE_ID AND P.ITE_ITEM_ID = VD.ITE_ITEM_ID
    LEFT JOIN WHOWNER.LK_ITE_ITEMS I ON P.SIT_SITE_ID = I.SIT_SITE_ID AND P.ITE_ITEM_ID = I.ITE_ITEM_ID
    WHERE 1=1
        AND P.ITE_ITEM_STATUS = 'ACTIVE'
    GROUP BY ALL
)

SELECT T1.*,
    SAFE_DIVIDE(PL1P_TIME_IN_STATUS_PERC , SUM(PL1P_TIME_IN_STATUS_PERC)  OVER (PARTITION BY SIT_SITE_ID, ITE_ITEM_ID, TIM_DAY) ) AS PL1P_TIME_IN_STATUS_POND,
FROM T1 AS T1
