SELECT P.TIM_DAY,
        EXTRACT(YEAR FROM P.TIM_DAY) *100 + EXTRACT(WEEK FROM P.TIM_DAY) AS WEEK,
        EXTRACT(YEAR FROM P.TIM_DAY) *100 + EXTRACT(MONTH FROM P.TIM_DAY) AS MONTH,
        EXTRACT(YEAR FROM P.TIM_DAY) *100 + EXTRACT(QUARTER FROM P.TIM_DAY) AS QUARTER,
        CASE WHEN EXTRACT (YEAR FROM DATE_TRUNC(P.TIM_DAY, WEEK)) = EXTRACT(YEAR FROM DATE_ADD(DATE_TRUNC(P.TIM_DAY, WEEK), INTERVAL 6 DAY)) 
            THEN
            CONCAT(CAST(DATE_TRUNC(P.TIM_DAY, WEEK)  AS STRING), " to ",CAST(DATE_ADD(DATE_TRUNC(P.TIM_DAY, WEEK), INTERVAL 6 DAY) AS STRING))
            ELSE 
            CONCAT(CAST(DATE_TRUNC(P.TIM_DAY, WEEK)  AS STRING), " to ",CAST(DATE(EXTRACT (YEAR FROM DATE_TRUNC(P.TIM_DAY, WEEK)),12,31) AS STRING)) 
            END AS WEEK_DETAIL,
        P.SIT_SITE_ID,
        P.ITE_ITEM_ID,
        P.VERTICAL,
        CASE 
            WHEN P.DOM_DOMAIN_AGG1 IN ('FOOTWEAR','APPAREL ACCESSORIES','APPAREL') THEN 'APPAREL'
            WHEN P.DOM_DOMAIN_AGG1 IN ('BEAUTY') THEN 'BEAUTY'
            ELSE NULL END AS SUBVERTICAL,
        P.DOM_DOMAIN_AGG1,
        P.DOM_DOMAIN_AGG2,
        P.ITE_ATT_BRAND,
        VD.SAP_VENDOR_ESTIMATED,
        I.ITE_ITEM_SUPERMARKET_FLG,
        I.ITE_ITEM_SCHEDULED_FLG,
        (SUM(COALESCE(TOTAL_VISITS_BB,0)) - SUM(COALESCE(VISITS_1P_BB,0))) AS VISITS_LBB,
        SUM(COALESCE(TOTAL_VISITS_BB,0)) AS VISITAS,
        (SUM(COALESCE(TOTAL_VISITS_BB,0)) - SUM(COALESCE(VISITS_1P_BB,0))) AS VISITS_LBB_V,
FROM WHOWNER.DM_MKP_PL1P_PRICING AS P
LEFT JOIN     
        (SELECT *
            , ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, ITE_ITEM_ID ORDER BY CASE WHEN SAP_VENDOR_ESTIMATED  IS NOT NULL THEN 1 ELSE 0 END DESC ) AS RW 
            FROM meli-bi-data.SBOX_PLANNING_1P.VW_BRANDS_VENDORS_ITEM_ID 
            QUALIFY RW =1
            ) VD ON P.SIT_SITE_ID = VD.SIT_SITE_ID AND P.ITE_ITEM_ID = VD.ITE_ITEM_ID
LEFT JOIN WHOWNER.LK_ITE_ITEMS I ON P.SIT_SITE_ID = I.SIT_SITE_ID AND P.ITE_ITEM_ID = I.ITE_ITEM_ID
WHERE 1=1
    AND P.ITE_ITEM_STATUS = 'ACTIVE'
GROUP BY ALL
