WITH CTE AS (

  SELECT 
    IM.TIM_DAY
    ,EXTRACT(YEAR FROM IM.TIM_DAY)*100 + EXTRACT(WEEK FROM IM.TIM_DAY) as WEEK
    ,EXTRACT(YEAR FROM IM.TIM_DAY)*100 + EXTRACT(MONTH FROM IM.TIM_DAY) as MONTH
    ,EXTRACT(YEAR FROM IM.TIM_DAY)*100 + EXTRACT(QUARTER FROM IM.TIM_DAY) as QUARTER
    ,IM.SIT_SITE_ID
    ,IM.ITE_ITEM_ID
    ,D.VERTICAL
    ,CASE 
          WHEN D.DOM_DOMAIN_AGG1 IN ('FOOTWEAR','APPAREL ACCESSORIES','APPAREL') THEN 'APPAREL'
          WHEN D.DOM_DOMAIN_AGG1 IN ('BEAUTY') THEN 'BEAUTY'
          ELSE NULL END AS SUBVERTICAL
    ,D.DOM_DOMAIN_AGG1
    ,D.DOM_DOMAIN_AGG2
    ,IM.ITE_ITEM_BRAND AS ITE_ATT_BRAND
    ,VD.SAP_VENDOR_ESTIMATED
    ,SUM(IM.SI) AS SI
    ,SUM(IM.GMV_IVA_DEDUCTED_LC) AS GMV_IVA_DEDUCTED_LC
    ,SUM(IM.SI_VALUED_ESTIMATED_LC) AS SI_VALUED_ESTIMATED_LC
    ,SUM(IM.AGREEMENT_AMOUNT_ESTIMATED_LC) AS AGREEMENT_AMOUNT_ESTIMATED_LC
    ,SUM(TCOUPON_AMOUNT_IVA_DEDUCTED_LC) AS TCOUPON_AMOUNT_IVA_DEDUCTED_LC
  -- ,V.VISITS_TOTALES
  FROM `meli-bi-data.WHOWNER.DM_MKP_PL1P_INVENTORY_METRICS` IM
  --LEFT JOIN `meli-bi-data.SBOX_PRICING1P.VISITAS_TOTALES` AS V ON IM.TIM_DAY = V.TIM_DAY AND IM.SIT_SITE_ID = V.SIT_SITE_ID AND IM.ITE_ITEM_ID = V.ITE_ITEM_ID
  LEFT JOIN `meli-bi-data.WHOWNER.LK_ITE_ITEM_DOMAINS` D ON IM.SIT_SITE_ID = D.SIT_SITE_ID AND IM.ITE_ITEM_ID = D.ITE_ITEM_ID
  LEFT JOIN     
  (SELECT *
    , ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, ITE_ITEM_ID ORDER BY CASE WHEN SAP_VENDOR_ESTIMATED  IS NOT NULL THEN 1 ELSE 0 END DESC ) AS RW 
    FROM meli-bi-data.SBOX_PLANNING_1P.VW_BRANDS_VENDORS_ITEM_ID 
    QUALIFY RW =1
    ) VD  ON VD.SIT_SITE_ID = IM.SIT_SITE_ID AND VD.ITE_ITEM_ID = IM.ITE_ITEM_ID

  WHERE IM.SIT_SITE_ID IN ('MLB','MLM','MLC','MLA','MCO')
    AND IM.TIM_DAY >= '2022-12-01'
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
)

SELECT C.*
  ,V.VISITS_TOTALES
FROM CTE AS C
LEFT JOIN  `meli-bi-data.SBOX_PRICING1P.VISITAS_TOTALES` AS V ON C.TIM_DAY = V.TIM_DAY AND C.SIT_SITE_ID = V.SIT_SITE_ID AND C.ITE_ITEM_ID = V.ITE_ITEM_ID
