-- version atualizada en 2024-03-21 por murilo.dasilva@mercadolivre.com
SELECT
    BB.TIM_DAY,
    EXTRACT(YEAR FROM BB.TIM_DAY) *100 + EXTRACT(WEEK FROM BB.TIM_DAY) AS WEEK,
    EXTRACT(YEAR FROM BB.TIM_DAY) *100 + EXTRACT(MONTH FROM BB.TIM_DAY) AS MONTH,
    EXTRACT(YEAR FROM BB.TIM_DAY) *100 + EXTRACT(QUARTER FROM BB.TIM_DAY) AS QUARTER,
    BB.SIT_SITE_ID,
    BB.ITE_ITEM_ID,
    BB.VERTICAL,
    CASE 
        WHEN BB.DOM_DOMAIN_AGG1 IN ('FOOTWEAR','APPAREL ACCESSORIES','APPAREL') THEN 'APPAREL'
        WHEN BB.DOM_DOMAIN_AGG1 IN ('BEAUTY') THEN 'BEAUTY'
        ELSE NULL END AS SUBVERTICAL,
    BB.DOM_DOMAIN_AGG1,
    BB.DOM_DOMAIN_AGG2,
    BB.ITE_ATT_BRAND,
    VD.SAP_VENDOR_ESTIMATED,
    SUM(CASE WHEN STATUS_BB_1P = 'pierde_1p' then TOTAL_VISITS_BB ELSE 0 END) AS VISITS_LBB,
    SUM(TOTAL_VISITS_BB) AS VISITAS,
    (COALESCE(SUM(TOTAL_VISITS_BB),0) - COALESCE(SUM(VISITS_1P),0)) AS VISITS_LBB_V,
  --(SUM(SI_BB) - SUM(SI_1P)) AS LBB_SI,
  --SUM(SI_BB) AS SI_BB,
  --(SUM(GMV_BB)- SUM(GMV_BB)) AS LBB_GMV,
  --SUM(GMV_BB) AS GMV_BB
FROM meli-bi-data.WHOWNER.DM_PL1P_PRICING_BUYBOX_PH BB--LEFT JOIN SBOX_PRICING1P.VISITAS_TOTALES V ON V.TIM_DAY = BB.TIM_DAY AND V.SIT_SITE_ID = BB.SIT_SITE_ID AND V.ITE_ITEM_ID = BB.ITE_ITEM_ID
--LEFT JOIN ORDERS O ON O.ORD_CREATED_DT = BB.TIM_DAY AND O.SIT_SITE_ID = BB.SIT_SITE_ID AND O.PRODUCT_ID = BB.PRD_PRODUCT_ID

LEFT JOIN     
  (SELECT *
    , ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, ITE_ITEM_ID ORDER BY CASE WHEN SAP_VENDOR_ESTIMATED  IS NOT NULL THEN 1 ELSE 0 END DESC ) AS RW 
    FROM meli-bi-data.SBOX_PLANNING_1P.VW_BRANDS_VENDORS_ITEM_ID 
    QUALIFY RW =1
    ) VD 
 ON VD.SIT_SITE_ID = BB.SIT_SITE_ID AND VD.ITE_ITEM_ID = BB.ITE_ITEM_ID
WHERE BB.SIT_SITE_ID IN ('MLB', 'MLM', 'MLC', 'MLA')
    AND BB.TIM_DAY >= '2022-12-01'
    --AND BB.DOM_DOMAIN_AGG1 IN ('FOOTWEAR','APPAREL ACCESSORIES','APPAREL','BEAUTY')
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12