WITH PKS AS (

  SELECT 
    PK.SITE AS SIT_SITE_ID,
    PK.VERTICAL,
    PK.AGG1 AS DOM_DOMAIN_AGG1,
    PK.AGG2 AS DOM_DOMAIN_AGG2,
    PK.VENDOR AS SAP_VENDOR_ESTIMATED,
    CAST(PK.SUPER_FLAG AS BOOLEAN) AS ITE_ITEM_SUPERMARKET_FLG,
    PK.LARGE_OVER_FLAG,
    CASE 
      WHEN PK.LARGE_OVER_FLAG = 0 THEN 'General Merchandise'
      WHEN PK.LARGE_OVER_FLAG = 1 THEN 'Oversize Merchandise'
      WHEN PK.LARGE_OVER_FLAG = 2 THEN 'Large Merchandise'
      ELSE NULL 
    END AS CLASIF_MC
  FROM 
    `meli-bi-data.SBOX_PRICING1P.TEMP_TS_PK_2025` PK
)

SELECT P.*
  ,ARRAY_AGG(DISTINCT(COALESCE(B.ITE_ATT_BRAND,"NULL"))) AS BRANDS
  ,SUM(VISITS_MATCH) - SUM(VISITS_EXPENSIVE) AS VISITS_COMPETITIVE
  ,SUM(VISITS_MATCH) AS VISITS_MATCH
FROM PKS P
LEFT JOIN SBOX_PRICING1P.TEMP_TS_2025_BPC B ON P.SIT_SITE_ID = B.SIT_SITE_ID AND P.DOM_DOMAIN_AGG2 = B.DOM_DOMAIN_AGG2 AND  LEFT(P.SAP_VENDOR_ESTIMATED,25) = LEFT(B.SAP_VENDOR_ESTIMATED,25) AND P.ITE_ITEM_SUPERMARKET_FLG = B.ITE_ITEM_SUPERMARKET_FLG AND CASE WHEN P.CLASIF_MC  != 'General Merchandise' THEN 1 ELSE 0 END = CASE WHEN B.CLASIF_MC  != 'General Merchandise' THEN 1 ELSE 0 END
GROUP BY ALL