SELECT
   t1.SIT_SITE_ID,
   LPAD(t1.SAP_SKU,18,'0') PL1P_OFFE_SAP_SKU,
   t1.BUYING_TERMS.SUGGESTED_RETAIL_PRICE.CURRENCY_ID PL1P_OFFE_SUGGESTED_PRICE_CURRENCY,
   U.CURRENCY_ID PL1P_OFFE_UNIT_PRICE_CURRENCY,
   C.PL1P_PO_LAST_UNIT_PRICE_AMOUNT_FILTER as PL1P_OFFE_UNIT_PRICE_AMOUNT,
   t1.status,
   t1.BUYING_TERMS.SUGGESTED_RETAIL_PRICE.AMOUNT as PL1P_OFFE_SUGGESTED_PRICE_AMOUNT
FROM
    `meli-bi-data.WHOWNER.LK_1P_OFFERING` as t1
LEFT JOIN UNNEST (BUYING_TERMS.UNIT_PRICES) U
INNER JOIN
    (select b.* from
        (
        select
          tt1.SAP_SKU,
          tt1.SIT_SITE_ID,
          tt1.PL1P_PO_UNIT_PRICE as PL1P_PO_LAST_UNIT_PRICE_AMOUNT_FILTER,
          row_number() over(partition by tt1.SIT_SITE_ID, tt1.SAP_SKU order by tt1.PL1P_PO_SAP_CREATED_DATE DESC, PL1P_PO_POSITION_DELETED ASC) as rn
        FROM
        `meli-bi-data.WHOWNER.LK_PL1P_PURCHASE_ORDER_DETAIL` as tt1
        WHERE
          tt1.PL1P_PO_CLASS_DESC = 'Pedido Buying Portal'
        ) b where b.rn=1
    ) C ON
    SAFE_CAST(t1.SAP_SKU as int64) = SAFE_CAST(C.SAP_SKU as int64) and t1.SIT_SITE_ID=C.SIT_SITE_ID
WHERE 1=1
    --LOWER(t1.status) = 'active' 
    AND NOT (COALESCE(t1.LABELS,'null') LIKE '%test%')
ORDER BY 1,2